services:
  raydium-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100m"
        restart: always